version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    command: sh -c "yarn install && yarn start"
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
